### ISSUE TITLE
Doesn't work for me (in Germany)

### ISSUE THREAD

**Issue by guevara777** [originallyus/node-red-contrib-alexa-local#1]
Hi,

thanks for the skill. I´m sorry to tell you that it doesnt work in germany (or for me in germany).

I use an iobroker-setup with an node-red-adapter (17.5) on an windows maschine. The log of iobroker says:

node-red.0 | 2017-10-09 23:43:12.671 | debug | 9 Oct 23:43:12 - [info] Started flows
-- | -- | -- | --
node-red.0 | 2017-10-09 23:43:12.671 | error |  
node-red.0 | 2017-10-09 23:43:12.671 | error | at process._tickCallback (internal/process/next_tick.js:104:9)
node-red.0 | 2017-10-09 23:43:12.671 | error | at _combinedTickCallback (internal/process/next_tick.js:73:7)
node-red.0 | 2017-10-09 23:43:12.671 | error | at Scheduler.drain (c:\smarthome\ioBroker\node_modules\when\lib\Scheduler.js:27:9)
node-red.0 | 2017-10-09 23:43:12.671 | error | at Scheduler._drain (c:\smarthome\ioBroker\node_modules\when\lib\Scheduler.js:62:19)
node-red.0 | 2017-10-09 23:43:12.671 | error | at Pending.run (c:\smarthome\ioBroker\node_modules\when\lib\makePromise.js:483:13)
node-red.0 | 2017-10-09 23:43:12.671 | error | at Fulfilled.when (c:\smarthome\ioBroker\node_modules\when\lib\makePromise.js:592:4)
node-red.0 | 2017-10-09 23:43:12.671 | error | at runContinuation1 (c:\smarthome\ioBroker\node_modules\when\lib\makePromise.js:804:4)
node-red.0 | 2017-10-09 23:43:12.671 | error | at tryCatchReject (c:\smarthome\ioBroker\node_modules\when\lib\makePromise.js:845:30)
node-red.0 | 2017-10-09 23:43:12.671 | error | at start (c:\smarthome\ioBroker\node_modules\node-red\red\runtime\nodes\flows\index.js:300:29)
node-red.0 | 2017-10-09 23:43:12.671 | error | at Flow.start (c:\smarthome\ioBroker\node_modules\node-red\red\runtime\nodes\flows\Flow.js:89:35)
node-red.0 | 2017-10-09 23:43:12.671 | error | at createNode (c:\smarthome\ioBroker\node_modules\node-red\red\runtime\nodes\flows\Flow.js:305:18)
node-red.0 | 2017-10-09 23:43:12.671 | error | at new AlexaLocalNode (c:\smarthome\ioBroker\iobroker-data\node-red\node_modules\node-red-contrib-alexa-local\index.js:25:20)
node-red.0 | 2017-10-09 23:43:12.671 | error | at Server.listen (net.js:1389:5)
node-red.0 | 2017-10-09 23:43:12.671 | error | at assertPort (internal/net.js:17:11)
**node-red.0 | 2017-10-09 23:43:12.671 | error | 9 Oct 23:43:12 - [error] [alexa-local:d350e649.46edd8] RangeError: "port" argument must be >= 0 and < 65536**

**Comment by torinnguyen** [comment]
Please try updating to the latest version. I have made a patch a moment ago.
It was just a small error in my code, probably has nothing to do with ioBroker or it being used in Germany.

**Comment by guevara777** [comment]
Perfect. Now just works fine! Thank you!
