### ISSUE TITLE
'on' variable of msg not showing in certain cases.

### ISSUE THREAD

**Issue by juggledad** [originallyus/node-red-contrib-alexa-local#10]
Node-RED version: v0.17.5
Node.js  version: v6.11.0
node-red-contrib-alexa-local version: 0.2.7
 
to reproduce
alexa node ---> debug node (display complete object

1) say "Alexa turn lamp off"
Debug shows:
10/13/2017, 9:48:22 AMnode: alexa output
msg : Object
object
on: false  <========= note this is in the debug
payload: "off"
change_direction: 0
bri: 0
bri_normalized: 0
device_name: "lamp"
light_id: "b4d1deed02b4c"
port: 57677
_msgid: "f772b7bc.2c99c8"

2) say "Alexa set lamp temperature to ten" 
Debug shows:
10/13/2017, 9:48:30 AMnode: alexa output
msg : Object
object   <========= missing 
bri: 10   <========= on status
payload: "off"
change_direction: 0
bri_normalized: 0.1
device_name: "frog"
light_id: "b4d1deed02b4c"
port: 57677
_msgid: "597cca59.1f6a24"

**Comment by torinnguyen** [comment]
This has been fixed in 0.2.8. Cheers.
