### ISSUE TITLE
Devices no longer discovered

### ISSUE THREAD

**Issue by mikejstb** [originallyus/node-red-contrib-alexa-local#103]
All has worked fine for a long time.
About 2-4 weeks ago Alexa no longer saw my devices.
Running Alexa discovery does not find any devices anymore

**Comment by DarrenSchwartz** [comment]
Same here, but I think mine has been broken a bit longer than that. Looked everywhere for a solution. Tried all kinds of fixes - updating, deleting/recreating nodes, even a complete reinstall of node red and modules. No joy.  

Would really love to have this working again. I'm tired of sitting in the dark.

**Comment by torinnguyen** [comment]
https://github.com/originallyus/node-red-contrib-alexa-local/issues/100#issuecomment-531777775

**Comment by mikejstb** [comment]
Thank you so much! I’ve started the conversion process and I think it's all working well.
Thanks again
