### ISSUE TITLE
When fed an input from a flow, Alexa node not producing an output

### ISSUE THREAD

**Issue by juggledad** [originallyus/node-red-contrib-alexa-local#11]
When you trigger the Alexa node from a flow, nothing comes out of the Alexa node
Node-RED version: v0.17.5
Node.js version: v6.11.0
node-red-contrib-alexa-local version: 0.2.7

Inject node  ----> Alexa node ---> debug node (display complete object)

to reproduce:
1) Set the inject node to inject a number of 5
2) deploy and press the inject button

Note that you see nothing from the debug node.

**Comment by torinnguyen** [comment]
This is the correct behavior. The input is solely for updating 'bri' value, it will not trigger the node.
I did this on purpose to avoid causing infinite loop when you hook the output of the Alexa flow back into the input of Alexa node.

**Comment by juggledad** [comment]
If I tell Alexa to turn the device off then use an input node to change the brighteness, the device is now on (??) but any flows down the line won't know the device's status....

loops are always possible after all any node with an input and output could be wired together that is a programers bug/problem

**Comment by torinnguyen** [comment]
I've just added an option for triggering the node from Input. Check out the node info for details.

**Comment by juggledad** [comment]
That woks great and adding a option looks like the best of both worlds!
