### ISSUE TITLE
Google home?

### ISSUE THREAD

**Issue by glynhudson** [originallyus/node-red-contrib-alexa-local#13]
Sorry if this is a silly question but could this flow ever be made to support Google Home? Am I correct in thinking that it emulates Hue? In that case might it work with Google Home?

**Comment by torinnguyen** [comment]
maybe. There are a few complications for this to work with Google Home. some of them are easy to overcome, some are simply dead-end depends on which platform and which version of Google Home users are using.
I'll definitely be trying to get it to work, seamlessly, no promises.
