### ISSUE TITLE
Deploy error

### ISSUE THREAD

**Issue by mikejstb** [originallyus/node-red-contrib-alexa-local#15]
When deploying a new node gets a "SyntaxError: Unexpected token =" error, plus Alexa cannot discover.
Node vs 0.3.2
Node red v0.15.5

**Comment by torinnguyen** [comment]
you can refer to the last few comments on issue #7. Someone has fixed this exact problem, not an issue with alexa node itself.

**Comment by mikejstb** [comment]
I saw this - 
Fixed it.
I noticed some weird disparity between running node-red from command line or as a service.

I tried running nr both ways, neither way fixed it.

Could I get some details on the proper way to run nr, details please?

**Comment by torinnguyen** [comment]
I don't know what is the proper way to run NodeRED, you need to look for this information on NodeRED website.
Personally, I'd run any NodeJS project using PM2.
