### ISSUE TITLE
Manual port configuration

### ISSUE THREAD

**Issue by twistedsanity** [originallyus/node-red-contrib-alexa-local#18]
Please forgive me if I have this wrong. 

I run node red on docker. I would prefer to leave it connected via the bridge network, therefore would like to be able to specify or override the ports chosen for each bridge. Is this possible?

**Comment by torinnguyen** [comment]
I am not familiar with docker. It is beyond the scope of this module.
There's another issue discussing about this #7 

The solution offered by one of the user was:
"easiest fix for now - is to run docker container with node red attached to host network (docker run --network=host ....)
but that may not suite all especially if you are using linking. another more complicated way is to use piperwork - https://github.com/jpetazzo/pipework"
