### ISSUE TITLE
Little Problem

### ISSUE THREAD

**Issue by dfloyd99** [originallyus/node-red-contrib-alexa-local#2]
So very please to see this appear, just what I needed, but followed instruction, created device called fred, link to debug node, then deployed and ask Alexa to find devices. So far so good, Alexa finds Fed, which she thinks is a Hue Light, but when I ask her to "Alexa Fred on" she refuses to play.

Any ideas

**Comment by dfloyd99** [comment]
Just playing and discovered calling the device "Fred Light" make this work?

**Comment by dfloyd99** [comment]
Now discovered that adding Light to after any defined name makes it work, can this be changed?

**Comment by torinnguyen** [comment]
i'm sorry this issue is beyond this library or any other libraries. That is just how Alexa interpret speech-to-text even before matching with devices name.

**Comment by dfloyd99** [comment]
It is not a big problem, I understand the limitations, but you may wish to make this clear in the documentation as it would seem a "unique device" name is not enough for it to just work.

**Comment by torinnguyen** [comment]
You do not really need to add "Light" at the back of your Device Name. Here are a few names without 'light' that I am currently using without a problem: Party Mode, Big boy, Bay Max, FishTank, Aircon, Chandelier, LED strip, etc.
I have also tested 'Fred' & 'Freddy', Alexa simply does not recognize those names. I have no idea why.

**Comment by dfloyd99** [comment]
Thanks, I will try a few more and see what I can find, excellent node by the way many thanks has saved me hours of work.
