### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by scargill** [originallyus/node-red-contrib-alexa-local#21]
If you are in node-red - and you replicate a device by copy-paste-rename - sometimes you get a message underneath to indicate address already in use.   

There's an easy way around it - don't copy-paste nodes - but as this usually works with nodes it would be nice if this could be fixed.

(other than that, this node works a treat)

**Comment by jonferreira** [comment]
I've experienced this myself too with v.3.2

**Comment by torinnguyen** [comment]
My Alexa node relies on Node ID (eg. "409174b1.1d019c") to uniquely assign an unused port to it. In general, when a node is copied/cloned, NodeRED suppose to give the new Node a new ID, which is fine for my port-assigning logic.

This error occurs when the copied node does not have an new NodeID.
Which I really don't know how to fix.
