### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by mugginsjm** [originallyus/node-red-contrib-alexa-local#22]
On deploy I get:

Error: EACCES: permission denied, mkdir '/nodered'

I don't know how to deal with this as nodered directory already exists.
thanks
John

**Comment by torinnguyen** [comment]
which user is NodeRED running with? it is recommended to use root to run it

**Comment by mugginsjm** [comment]
Hi
Sorry but my linux knowledge is rubbish. I have installed NodeRed via Pete Scargill's script and don't know
how to find this info.

**Comment by torinnguyen** [comment]
I'm sorry that is beyond my help. Different linux setup will have different configuration. How you have installed NodeRED in the first place will also make a different.

**Comment by b3nj1** [comment]
This worked for me when I run as the user that owns the node-red process. Ideally, the package would not try to make a directory at / level, but this works around it (again for me):
```
sudo mkdir /nodered
sudo chown ${USER} /nodered

```
