### ISSUE TITLE
Cannot discover nodes created on node-red running using docker

### ISSUE THREAD

**Issue by narioinc** [originallyus/node-red-contrib-alexa-local#23]
Hi Team,

First, I would like to thank the team behind this awesome plugin. It has helped me setup some complex workflows with my smart home relays and Alexa. 

I have one issue that I am facing now. I have installed docker on windows and wanted to install Node-red as a docker instance. I use the foloowing commands to start the node-red instance:

docker run -it -p 1880:1880 --name mynodered nodered/node-red-docker

The node-red installation goes through without a hitch and I am also able to install the alexa local node successfully. But Alexa is unable to find the virtual device I create. I have some doubt on the fact that the node replicates a Hue device on a particular port but since now node-red runs off docker there is some issue with alexa finding the port. My earlier setup with node-red on the raspberry pi 3 worked perfectly. 

Could the team please help me understand the issue and if i can resolve the same on my end

Thanks once again for the cool little node.!!!

**Comment by torinnguyen** [comment]
I am not familiar with docker. It is beyond the scope of this module.
There's another issue discussing about this #7

The solution offered by one of the user was:
"easiest fix for now - is to run docker container with node red attached to host network (docker run --network=host ....)
but that may not suite all especially if you are using linking. another more complicated way is to use piperwork - https://github.com/jpetazzo/pipework"

**Comment by narioinc** [comment]
Thanks for the pointer torinnguyen

Ill have a look at the solution.

**Comment by twistedsanity** [comment]
So it can work with docker, but I am only aware of two ways.

1) let us specify the port used for each device manually this way pre
container start up we can specify multiple ports to be preassigned.

2) enable promiscuous mode on the nic attached to node red. Create a
macvlan network and attached node red to that assigning a dedicated IP on
the same as the host network.

I have option 2 running and working at the moment. Its not ideal but it
works. I am mobile and unable to give full details via my phone but will
document further if anyone is interested.

Thanks

Matt

**Comment by JamesMcCarthy79** [comment]
@twistedsanity I'd be interested in how you set this up.
