### ISSUE TITLE
Recognize difference between "on" and "set brightness"

### ISSUE THREAD

**Issue by Jaxon77** [originallyus/node-red-contrib-alexa-local#24]
First of all thank you for your work on this node. I replaced all Wemo Emulator nodes with yours and it works very well.
But i noticed that i cannot differ if the payload was triggered by an "on" or "bright" command. As i would like to do some special action if the command was an "on" instead of an "set bright" it would be nice to see that on the payload.

**Comment by torinnguyen** [comment]
This is now available via output parameter msg.on_off_command == true
Please update to latest version
