### ISSUE TITLE
Permission Denied error

### ISSUE THREAD

**Issue by mikecay** [originallyus/node-red-contrib-alexa-local#25]
Hi,

I just installed 0.3.2 today in node-red 0.17.5 and when I add and configure the alexa local node in a flow I get the following error

Error: EACCES: permission denied, mkdir '/nodered'

Any idea what the problem may be?

Thank you,

Mike

**Comment by jonferreira** [comment]
I had the same problem, just manually create the necessary folder

**Comment by torinnguyen** [comment]
This Alexa node is using 'nodered/alexa-local/persist/' folder to persist some internal information.
Normally it is automatic created in the home folder of whatever user is running NodeRED, and does not cause any issue.

If you have special permission or non-standard NodeRED setup, please create that folder manually & give it a write permission for NodeRED's system user.
