### ISSUE TITLE
alexa ios app 

### ISSUE THREAD

**Issue by Toshibass** [originallyus/node-red-contrib-alexa-local#27]
Hi I have been using the node-red-contrib-wemo-emulator but thought I would give this node a try, so I just installed node-red-contrib-alexa-local and via node-red its working perfectly, I can send off, on or a value and I see the expected output in a debug node 'great' however my question is regarding the alexa ios app, obviously after I created the 'alexa local node' I went to Add Device in the alexa app, it found the Device immediately and to my surprise it appears that I could/can control the Device directly from the app, (Bonus ?) however when I press the picture to turn **off** the lamp on the app the 'alexa local node' indeed turns **off** but after a moment the app changes from saying the light is off to Light is on Brightness set to 49% again, same same if I set the brightness to say 5% the 'alexa local node' outputs the value but after a moment the app changes changes back to Light is on Brightness set to 49% again, see attached...

So whist this issue it is not a deal breaker as I will primary use Node-Red for control (and as I said control from the alexa app was a surprise for me) I just wondered if this was a bug or something new that has gone unnoticed.

![img_0090](https://user-images.githubusercontent.com/6310911/33129145-d5fed5de-cf86-11e7-86cb-f69994dc010a.JPG)
![img_0091](https://user-images.githubusercontent.com/6310911/33129148-d7b881ae-cf86-11e7-956b-034b3dc5ad33.JPG)

**Comment by mB-PiBox** [comment]
This is probably a result of Amazon changing the setup of the Amazon Alexa app. Prior to recent changes to the Alexa app, it never sent a "GetBinaryState" request. Now with the recent changes to the Alexa app, its requesting the state of the "smart device." However this node does not having any code to respond to that request from the Alexa app.

**Comment by torinnguyen** [comment]
Please refer to issue #19 

> It is implemented that way in order to correct detect increase/decrease commands.
Everything was designed to work correctly only in NodeRed.
It is possible to return the correct status to Alexa, however, the node will lose a few capability and will not be as versatile as it is now.

> Btw, my Alexa app never has that slider, not on iOS nor Android.

**Comment by UberSlackr** [comment]
The Alexa app on my iPhone and iPad Pro show the same slider, with the same result of always defaulting to on 49%. https://imgur.com/gallery/NoVLL

You don’t have to have it return the current state. Could just have it dump the request. It’s acting as it is because the “smart device” is returning an error to the state request. 

Thought it was designed to allow Alexa to interact with node-red? Which takes the scope outside of node-red. As the issue always effects properly using Routines with Alexa, which breaks some functionality of the node within node-red
