### ISSUE TITLE
Please add support for "toggle" state.

### ISSUE THREAD

**Issue by mB-PiBox** [originallyus/node-red-contrib-alexa-local#28]
Would be nice if there was an option to toggle current state. So that the emulated "device" could also be control via a button on node-dashboard.

**Comment by torinnguyen** [comment]
This is now available in the latest version.
You simply send it a msg.payload = "toggle" via Trigger node, Button node or Function node.
Remember to activate Input Trigger option in Alexa node.

![node-red 2017-11-28 16-18-47](https://user-images.githubusercontent.com/767320/33311594-dce60496-d457-11e7-83d7-ff084c826d7a.png)
