### ISSUE TITLE
Use a predetermined port range (config?)

### ISSUE THREAD

**Issue by spants** [originallyus/node-red-contrib-alexa-local#3]
Could it use a fixed range of ports instead of random ports(?) - that way we can use it in Docker images too.

**Comment by hardillb** [comment]
How do you forward SSDP broadcast packets to a docker container?

**Comment by torinnguyen** [comment]
In order to make it dead-simple to use, I have decided to make the port selection automatic. Let me think of a way to implement it without compromising on user experience.
However, do note that the port number given for a Node will never change even after a NodeRED reboot.

**Comment by torinnguyen** [comment]
@hardillb I don't have enough knowledge of docker to answer your question. The SSDP service being used here always listen on port 1900. I believe it's UDP traffic.

**Comment by hardillb** [comment]
That question was more aimed at @spants. The problem will be that while the port may be fixed it is a broadcast address. I've had issues with firewall rules for SSDP for the WeMo nodes in the Node-RED core set so just wanted to make him aware it could still be a problem.

**Comment by hardillb** [comment]
That doesn't work for when you are doing the discovery (not replying to a discovery request) because the reply come from a unknown IP address on a random port, it needs a iptables helper module to track the outgoing requests.

**Comment by spants** [comment]
@hardillb weird that it did work for me then, must have been lucky!....... I will close this.

**Comment by lesterchia1** [comment]
Hi Spants, the node work for the MQTT but it didn't work when i connect the node to rpi-gpio out node pin 11. How do you do it? Appreciate for you advise.

**Comment by tfatykhov** [comment]
easiest fix for now - is to run docker container with node red attached to host network but that may not suite all especially if you are using linking. another more complicated way is to use piperwork - https://github.com/jpetazzo/pipework

**Comment by MosquitoD4K** [comment]
Okay, so I run node-red on a windows server and need to define open ports manually in the firewall. This feature would be great to have. It would be nice to be able to configure the port of a node.
