### ISSUE TITLE
Node not deploying

### ISSUE THREAD

**Issue by alport** [originallyus/node-red-contrib-alexa-local#31]
With a new RPi 3B loaded with Stretch, when I try and deploy the node, I get:

2017/11/26, 21:56:46node: b736c312.96e5cmsg : error
"SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode"
2017/11/26, 21:56:46node: 52966ee5.c9ca8
msg : error
"SyntaxError: Unexpected token ="

Any ideas?

**Comment by torinnguyen** [comment]
please try updating to version 0.3.3

**Comment by torinnguyen** [comment]
Also, please refer to issue #7
