### ISSUE TITLE
Add support for color temperature, hue

### ISSUE THREAD

**Issue by kamsvag** [originallyus/node-red-contrib-alexa-local#32]
It would be nice to be able to change color temperature by saying 'Alexa turn kitch warm/cold/medium'.

**Comment by torinnguyen** [comment]
It is not possible with this implementation #16 
You'll have to use the other Alexa node with Alexa Skills via the cloud for that.

**Comment by koraysels** [comment]
Is that so ? This nodered node works by emulating a phiips hue device. Philips hue devices are already detected as a color light in alexa. It just lacks an implementation.
