### ISSUE TITLE
removing devices from alexa

### ISSUE THREAD

**Issue by r-x-s** [originallyus/node-red-contrib-alexa-local#37]
Hi,
is there any way to remove devices created with this node from alexa?  I created a few test ones to play around with but they are just cluttering up my alexa app now that I have added nodes for real devices.

Thanks for the work on this,  it's awesome!

**Comment by torinnguyen** [comment]
Deleting device can be done inside Alexa app as normal. Please google for
instructions.

This has nothing to do with Alexa node in NodeRed

**Comment by r-x-s** [comment]
Ok.  I couldn't find any way to do so (having googled) and wondered if it was to do with the way the node emulated a Phillips hue device, this requiring a specific approach for removal to work

**Comment by r-x-s** [comment]
The node-red alexa devices can be disabled but not deleted that I can see
