### ISSUE TITLE
Brighter / Dimmer inject

### ISSUE THREAD

**Issue by fraser73** [originallyus/node-red-contrib-alexa-local#38]
Is it possible to format a message to inject "brighter" or "dimmer" into the alexia-local node? I can see how to do on/off/absolute brightness, but I can't see how I might emulate the voice request of "alexa, make living room lights brighter".

**Comment by torinnguyen** [comment]
i'll work on that

**Comment by torinnguyen** [comment]
It's now supported in v0.3.17

![image](https://user-images.githubusercontent.com/767320/37322042-f7295576-26ad-11e8-86a4-dae0d9b2846f.png)
