### ISSUE TITLE
Alexa cannot discover new device

### ISSUE THREAD

**Issue by bh4rtp** [originallyus/node-red-contrib-alexa-local#39]
I am using the latest Node-RED, alexa-local. The flow is very simple. It runs on local VirutalBox VM. My Amazon Echo Dot 2 cannot find new alexa-local devices.
```
21 Dec 00:54:47 - [info] Node-RED version: v0.17.5
21 Dec 00:54:47 - [info] Node.js  version: v8.9.1
21 Dec 00:54:47 - [info] Linux 4.4.0-104-generic x64 LE
21 Dec 00:54:48 - [info] Loading palette nodes
21 Dec 00:54:48 - [info] Dashboard version 2.6.2 started at /ui
```

**Comment by bh4rtp** [comment]
does discover new devices relate with network setup? this is my configuration.
1. virtual box ubuntu 16.04 vm runs on a win10 laptop
2. install node-red, alexa-loal on the vm
3. both laptop and echo dot 2 connect home wifi
4. add an alexa-local and a debug node into the flow and deploy it
5. ask `alexa, discover devices`
6. alexa replies `no new devices found`

**Comment by Malarcy** [comment]
similar issue

I create the node - tell alexa to discover - the node status changes to  "Discovery" alexa completes discovery and says "no new devices"

In the console where I launched node-red I see the GET for setup.xml from the alexa ip address.

**Comment by bh4rtp** [comment]
i managed to solve the problem. it is because the ssdp protocol is used to discover devices. running under virtual machine, the device cannot be discovered. so i changed just an hour ago to run directly on the win10 host. now the nodes can be discovered and alexa works perfectly.
btw, the latest alexa-local version is used.

**Comment by Malarcy** [comment]
Ok. 

Mine is a different issue then. I am not using vm’s and I am on a Linux host. 

I will open a new issue.
