### ISSUE TITLE
Couple of notes

### ISSUE THREAD

**Issue by hardillb** [originallyus/node-red-contrib-alexa-local#4]
1. Please add the git URL to the package.json so we can find it easier from npm and flows.nodered.org
2. This is just emulating Hue and Wemo devices at the moment, so this means not lock or AV support?

**Comment by torinnguyen** [comment]
1. git url has been added. sorry i'm pretty new to npm publishing.
2.

**Comment by hardillb** [comment]
There is no built in local support for locks (all the different vendors have their own proprietary cloud solutions) in the Echo that I know of.

There is also the heating/cooling control in the ever growing home skill api. This is why I did with a cloud component for the node-red-contrib-alexa-home-skill node.

I think you're going to end up only being ale to support the modes that match up to the switch and lighting control systems that Hue/WeMo can cover.

**Comment by torinnguyen** [comment]
I believe in simplifying user experience for new users. Once users are familiar enough with the ecosystem they can move on to your cloud-based solution.
