### ISSUE TITLE
Alexa does not discover the "devices"

### ISSUE THREAD

**Issue by Malarcy** [originallyus/node-red-contrib-alexa-local#40]
21 Dec 12:00:24 - [info] Node-RED version: v0.17.5
21 Dec 12:00:24 - [info] Node.js  version: v8.9.3
21 Dec 12:00:24 - [info] Linux 4.10.0-42-generic x64 LE

Running on ubuntu 16.04 LTS desktop 

1) flow created - simple alexa-local node output to debug - deploys ok
2) alexa, discover devices
3) node status changes to discovey
4) node-red console outputs message says

3ee08a4ec4bdb6 Paul GET /upnp/amazon-ha-bridge/setup.xml ::ffff:192.168.0.67
Sending setup.xml to ::ffff:192.168.0.67

"Paul" is the node name, 192.168.0.67 is alexa ip address

5) alexa completes discovery, says @no new smart home devices"
6) node status stays in "discovery"

Alexa unit in this case is a echo plus - but I have also tried from alexa app on phone - can retry with a dot if we think that is a contributing factor

**Comment by torinnguyen** [comment]
There's an unconfirmed issue with Echo Plus not discovering devices.
Please try on Echo Dot.
Virtual Alexa on app, FireTV Stick do not have discovery capability. This is confirmed.

**Comment by Malarcy** [comment]
thats it - restarted node red and switched to DOT discovery and control look to working OK - i can help with debug on the plus if required.
