### ISSUE TITLE
Local doesn't work?

### ISSUE THREAD

**Issue by Jasurf** [originallyus/node-red-contrib-alexa-local#41]
Hi, I cannot figure out why this does not work for me.  I have my PC running Node-Red with an "Alexa-Local" configured.  My PC and Echo-Dot are on the same wifi.  Alexa does not discover the new device.
There must be another step in setting this up!   Thank you for your help!

**Comment by torinnguyen** [comment]
Please start troubleshooting by looking at the closed issues.
https://github.com/originallyus/node-red-contrib-alexa-local/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+discover
