### ISSUE TITLE
Alexa iOS App Showing Wrong State

### ISSUE THREAD

**Issue by strangedesign13** [originallyus/node-red-contrib-alexa-local#46]
Just installed 0.3.12 on NodeRed 17.5. It seems to be working fine but even though my test light "status" is fine in NodeRed (shows "off") it seems that the in the iOS app the light shows on. And on any toggle off in the app, the light shuts off, but the iOS app UI quickly goes to "On". Light stays off though, and NodeRed shows the light as off.

**Comment by torinnguyen** [comment]
This is fixed in version 0.3.16 onwards
