### ISSUE TITLE
Other capabilities

### ISSUE THREAD

**Issue by adidoes** [originallyus/node-red-contrib-alexa-local#48]
So I have alexa-local setup to turn my tv on/off and I wanted to add a mute capability as well so I created a "Mute Living Room TV" node but when I say the command to alexa it says the device doesn't support that. 

Where can I find more info about this? 

Are there devices that support more than just on/off/brightness without a custom skill?

Thanks!

**Comment by torinnguyen** [comment]
this node emulate a light bulb. Mute capability will never apply to this.
