### ISSUE TITLE
Alexa Local don't work

### ISSUE THREAD

**Issue by uiff** [originallyus/node-red-contrib-alexa-local#51]
I exported my flow because of a bug on the Raspbian. After I reinstalled everything. The flow was imported again, but unfortunately, they do not work anymore.

The node does not show anything below, such as a port.

Can someone help me here?

Thanks in advance

**Comment by uiff** [comment]
![unbenannt](https://user-images.githubusercontent.com/24621258/37057238-049278b8-2187-11e8-90d6-f881e68b8441.JPG)

**Comment by torinnguyen** [comment]
take a look at the log. I can't troubleshoot anything from your screenshot.
