### ISSUE TITLE
[Request]Any chance of getting this node an option to prevent infinite loop.

### ISSUE THREAD

**Issue by wongnam** [originallyus/node-red-contrib-alexa-local#54]
Hi, 
Thank you for creating this node. it's awesome.

Is there any chance of getting this node an option to prevent infinite loop.
For example, create an check box for us to chose whether allow msg arrives on input, to pass through to output or not.
because sometimes i want to let input node to feedback the status back to inside Alexa app if the external switch toggled the light on/off. but i don't want the msg pass through to the output.

![image](https://user-images.githubusercontent.com/36041520/37384465-adea86e4-2781-11e8-9916-7fd676abaaf0.png)

![image](https://user-images.githubusercontent.com/36041520/37384499-e20052a6-2781-11e8-994d-e8e8c50124b6.png)

Thanks you.

**Comment by torinnguyen** [comment]
untick this 

![image](https://user-images.githubusercontent.com/767320/37384572-44bcd3c4-2782-11e8-8a35-fb438552672b.png)

**Comment by wongnam** [comment]
if untick this check box that the input status is not updated to Alexa App.

**Comment by torinnguyen** [comment]
this function is not available. you can add a custom function node at the output and check the 'topic' parameter to stop the message.

**Comment by wongnam** [comment]
okay, i'll do it this way.
Thank you for your advice.

**Comment by thePhilipp** [comment]
hi wongnam,
here is my solution for this Problem
https://github.com/originallyus/node-red-contrib-alexa-local/issues/45
look at the end

**Comment by torinnguyen** [comment]
I have no problem using SONOFF + UI Switch with Alexa Node.
Both Alexa app & the UI Switch is updated correctly, no infinite loop.
<img width="740" alt="node-red 2018-04-06 05-59-38" src="https://user-images.githubusercontent.com/767320/38396013-046353f8-3960-11e8-9aeb-40f13fbf0156.png">

Video demo showing no infinite loop http://take.ms/0D8bF
