### ISSUE TITLE
Echo Spot discovery does not work 

### ISSUE THREAD

**Issue by m0rph2k** [originallyus/node-red-contrib-alexa-local#56]
Hi

Echo Spot discovery does not work 
Echo Spot --> the node detects that alexa is looking for devices (discovery) but it is not found.
Echo Dot Gen2 -- >works

node-red Adapter 1.5.1
node-red-contrib-alexa-local 0.3.19

**Comment by IDmedia** [comment]
Sounds like I'm having the same issue, but with the Amazon Echo (Gen2). When asking that device to search for new smart devices, nothing is found, but if I do the same on the Echo Dot (Gen2) it works.

**Comment by torinnguyen** [comment]
FWIW, Echo Show does not have the capability to perform local device discovery. Maybe it's the same case for Echo Spot.
Echo Gen 2 (not Dot Gen 2) & Echo Plus are confirmed to have problem discovery.
I'm closing this issue, please continue discussion in issue #47
