### ISSUE TITLE
"light bri is null in storage"

### ISSUE THREAD

**Issue by RaymondMouthaan** [originallyus/node-red-contrib-alexa-local#60]
Using node-red-contrib-alexa-local 0.3.22 gives the message "light bri is null in storage" in the debug tab, as well in the console logging ([warn] light bri is null in storage). 

This happens every time a "turn on" or "turn off" command is given to Alexa. The node works perfectly fine.  When a command like "set light to 50%" is given the message doesn't occur.

**Test case**

1. When a command like "turn on" has been given, a new file located at ../alexa-local/persist is created with the following content:
```
{"key":"35a66de6dabb1a_state","value":true}
```
This command **shows** the message "light bri is null in storage".

2. When a command like "set light to 50%" has been given, a new file located at ../alexa-local/persist is created with the following content:
```
{"key":"35a66de6dabb1a_bri","value":127}
```
This command **doesn't show** the message "light bri is null in storage".

3. When a command like "turn off" has been given, the file from step 1 gets updated with the following content:
```
{"key":"35a66de6dabb1a_state","value":false}
```
This command **doesn't show** the message "light bri is null in storage"!

4. When a command like "turn on" has been given, the file from step 1 gets updated with the following content:
```
{"key":"35a66de6dabb1a_state","value":true}
```
This command **doesn't show** the message "light bri is null in storage"!

5. Then after deleting all files from ../alexa-local/persist, the message **doesn't show** for the specific node!

**Conclusion/workaround**
For each newly placed alexa-local node a "set <node_name> to 50%" command should be given to avoid the message "light bri is null in storage".

**Comment by torinnguyen** [comment]
Please update to newer version. The warning message is removed.

**Comment by RaymondMouthaan** [comment]
Noticed that, thanks for this great node :-)
