### ISSUE TITLE
Fire Tablet 10HD, no discovery

### ISSUE THREAD

**Issue by MagicReload** [originallyus/node-red-contrib-alexa-local#68]
![alexa node](https://user-images.githubusercontent.com/43683766/46226895-fc798f80-c35d-11e8-83dd-ff6826dc9723.JPG)
Hello,
i use Hass.IO with the latest Node-Red and afetr i add the node from the "node-red-contrib-alexa-local",
i get a yellow sign below the node telling me "discovery", but my Alexa Tablet tells me all the time there is no new device found.
sae Problem with my Android Smartphone 
Is it not possible to add new Devices via handsfree Fire tablet?
Or do i miss a crucial step?

Thx
Magic Reload

**Comment by torinnguyen** [comment]
Not supported.
