### ISSUE TITLE
Wrong ip in msg-object

### ISSUE THREAD

**Issue by ChrisStain87** [originallyus/node-red-contrib-alexa-local#71]
Hey!

I have two echo devices, 10.64.110.107 and 108. I've startet testing with device 107. The Msg output is:

{"on":true,"from":"::ffff:10.64.110.107","on_off_command":true,"payload":"on","change_direction":0,"bri":63,"bri_normalized":0.63,"device_name":"Licht","light_id":"5ed54b0bff69c4","port":42053,"_msgid":"b857fdd9.faa7b"}

which is fine. When i try to to the same with the 108 device i get the exact same result. 

Any idea? I think the from: part should be different, or am i wrong?

Best regards

**Comment by torinnguyen** [comment]
It is not wrong.
The "from:" address is always the first Echo device that discovers this node. It is not the Echo device that you are speaking to.
This is just how Alexa system works. They always issue command from the Echo device that discover the node.
