### ISSUE TITLE
Just suddenly quit working!

### ISSUE THREAD

**Issue by Jasurf** [originallyus/node-red-contrib-alexa-local#73]
Hi!  So this was working fine. then suddenly all of my "Alexa local" devices in my Alexa app just disappeared! I cannot re-discover them!
Nothing changed!  I did not do any updates to Node_Red, Wifi, nothing!  In fact I have not done any changes for months!  Node-Red is still up and running and working fine besides "Alexa Local". Why would all of my Alexa-Local devices just suddenly disappear from device list and never come back and never re-discover?

**Comment by moonlitknight** [comment]
Same experience here. No changes, everything rebooted, but suddenly not working.

**Comment by pinoyyid** [comment]
Suddenly working again. It looks like something at Amazaon's end

**Comment by Jasurf** [comment]
Same here!  All working again.  Looks like we can close this thread!  :)
