### ISSUE TITLE
identify the alexa device that received the command

### ISSUE THREAD

**Issue by nnhhuu** [originallyus/node-red-contrib-alexa-local#78]
hello guys,   first thank you for this node, it helps me a lot....  
i'm trying to identify the alexa device who received the command, i'm trying to send it back an answer to that device.
The message brings an IP address (it belongs to an echo device), but it is always the same ip address no matter the device who receive the order.

on: true
**from: "::ffff:192.168.10.231"**
on_off_command: true
payload: "on"
change_direction: 0
bri: 100
bri_normalized: 1
device_name: "Door Status"
light_id: "989d852eec24e8"

thank you

**Comment by MrBLJ** [comment]
Came here to ask excatly the same ! This would be a nice feature indeed.

**Comment by thmeger** [comment]
Yes, it is possible to get the IP from that device that has noticed the command?

**Comment by torinnguyen** [comment]
It is not possible. the "from:" address is always the first Echo device that discovers this node. It is not the Echo device that you are speaking to.
This is just how Alexa system works. They always issue command from the Echo device that discover the node.
