### ISSUE TITLE
image missing in info box

### ISSUE THREAD

**Issue by juggledad** [originallyus/node-red-contrib-alexa-local#8]
V0.2.2

When you select the 'Info' tab for Alexa local under the 'How to Use' section, there is a missing image icon being displayed. Currently it is looking for the image from
`https://raw.githubusercontent.com/originallyus/node-red-contrib-alexa-local/master/screenshot3.png`

the image (screenshot3.png) does exist in the 'node-red-contrib-alexa-local' folder

**Comment by torinnguyen** [comment]
Thanks! Fixed that.
