### ISSUE TITLE
Node do not discover with https

### ISSUE THREAD

**Issue by Jury1985** [originallyus/node-red-contrib-alexa-local#83]
hello,
i have a problem.
i change my node red to the https protokoll, certyfied by letsencrypt.
and now the node ist not working.
i thing the problem is that the node discover on the http protokoll, but i am not sure.
it ist possible to change it in an option.

i hope you can help me

**Comment by wongnam** [comment]
@Jury1985 FYI. I am still using Alexa-local node and still can discovery my device via Echo dot 2nd even my Node-Red is https (self-sign) .

**Comment by Jury1985** [comment]
I use the Echo dot 2nd gen too.
 than i do not understand the problem, have you change some options in node red that can work?
 have you activate the username and the password for https too?
i think this can be the reason too, that it is do not recover

**Comment by Jury1985** [comment]
why is it closed?

**Comment by Jury1985** [comment]
i get this failure 

"Error: [PARSE-ERROR] /home/pi/.node-red/alexa-local/persist/34da78d447138905afdaf3635d055ce1 does not look like a valid storage file!"

**Comment by Jury1985** [comment]
i delete this Folder, an the Problem was fixed.
