### ISSUE TITLE
Alexa Reports Device Malfunction

### ISSUE THREAD

**Issue by peteakalad** [originallyus/node-red-contrib-alexa-local#98]
Lights triggered via alexa local were working fine until today.

Alexa reports device malfunction and cannot turn on light.

Removing device and rediscovering - device is not found again.

I have tried restarting node-red with no luck either.

Something changed on alexa side to break this?

**Comment by peteakalad** [comment]
Changed my flows to use node-red-contrib-alexa-home - its working for me..

**Comment by nepeee** [comment]
Same here :(

**Comment by kuenzeln** [comment]
Same here =/

**Comment by DaKingComeBack** [comment]
Same here :/
Everything was working well a couple of hours before

**Comment by LakeCruiser** [comment]
Same here :/

**Comment by jk2020** [comment]
Same here; Any hint how to get it back working?

**Comment by jk2020** [comment]
> ed my flows to use node-red-contrib-alexa-home - its working for me..

does not work for me. Get loads of errors when trying to install

`
pi@smarthome:~ $ cd .node-red
pi@smarthome:~/.node-red $
pi@smarthome:~/.node-red $ sudo npm install node-red-contrib-alexa-home

> usb@1.6.0 install /home/pi/.node-red/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.2.5
prebuild-install WARN install EACCES: permission denied, access '/root/.npm'
gyp WARN EACCES user "pi" does not have permission to access the dev dir "/root/.cache/node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/.node-red/node_modules/usb/build'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/usb
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok

> bluetooth-hci-socket@0.5.1 install /home/pi/.node-red/node_modules/bluetooth-hci-socket
> node-gyp rebuild

gyp WARN EACCES user "pi" does not have permission to access the dev dir "/root/.cache/node-gyp/10.15.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/.node-red/node_modules/bluetooth-hci-socket/build'
gyp ERR! System Linux 4.14.98-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/.node-red/node_modules/bluetooth-hci-socket
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm WARN node-red-project@0.0.1 No repository field.
npm WARN node-red-project@0.0.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.0 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.6.0 install: `prebuild-install --verbose || node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ node-red-contrib-alexa-home@1.1.2
added 42 packages from 32 contributors and audited 1137 packages in 19.42s
found 2 vulnerabilities (1 low, 1 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details
pi@smarthome:~/.node-red $
`

**Comment by paulcontboxx** [comment]
Same here.

**Comment by J-Paul0815** [comment]
same

**Comment by msauto** [comment]
Same here, this has always happened every now and then randomly as long as i have used the alexa local node. But few and far between and the remedy was to delete the device and search for devices again sometimes several times before it would find the device but always found the device. Then go back and add the device to any routines from before deletion and all would be well for usually at least a month. But now it seems around a week ago i started having the "sorry xyz device is not responding please check its power supply" error message on about every other request on random devices and removing and reinstalling isn't working either. I did notice that in the alexa app it says i have 49 devices and the number doesn't change when i add new ones or delete broken ones. I wonder if amazon has put the device limit back in play? I seem to remember the limit being around 49 in the beginning.

**Comment by mah086** [comment]
Alexa started reporting "Sorry, provider is having trouble" about a day ago. I've tried adding new nodes but Alexa cannot find them. This is similar to past issues, but the reported error is different and the old resolutions do not work including a full reset of the system and router.

**Comment by guardiande** [comment]
Switching to Alexa Home helped for me. Be sure to read the (short) documentation thoroughly regarding port 80.

**Comment by peteakalad** [comment]
@guardiande yes good call - alexa home worked for my dots for a while till the other day, needed to update it and expose it via port 80 like those intructions say.  

In the absence of any update on this repo - RIP alexa local you served us well.

**Comment by LakeCruiser** [comment]
Does this apply to Hassio?  I can't understand how to update or configure port 80.

**Comment by peteakalad** [comment]
Hassio has its own Alexa plugin via their paid HA cloud thing I think?  Are you using it and its broken?

You expose the alexa hub for all your node-red devices on port 80 - either with an iptables rule or change the actual port to 80.  See the instructions here;
https://github.com/mabunixda/node-red-contrib-alexa-home

**Comment by LakeCruiser** [comment]
No, I don't use the HA cloud.  I can't get any of my Alexa nodes to work anymore.  I'm just about sick of the whole diy smarthome rat race.  Just when you get everything working somebody has to change it.  WAF factor has went from 100 to 0 in 2 weeks.  Maybe some one will come up with a YouTube video on it.  I just got our bedroom blinds opening on voice command and automatically opening every workday at 6:45 !  Now none of that works anymore.

**Comment by LakeCruiser** [comment]
Ok, I broke down and subscribed to the HA Cloud. 307 devices discovered! $5 per month is a small price to pay for what I have been through the past two weeks! 🤯 Everything seems to be working again!  Thanks @peteakalad

**Comment by borolo222** [comment]
Any updates on this? all my devices are down..

**Comment by torinnguyen** [comment]
Refer to my comment here 
https://github.com/originallyus/node-red-contrib-alexa-local/issues/100#issuecomment-531777775
