### ISSUE TITLE
new devices are no longer found, existing ones do not react anymore

### ISSUE THREAD

**Issue by x3l4c0d3** [originallyus/node-red-contrib-alexa-local#99]
For some days I have the phenomenon that my equipment can not be reached. If I delete these from Alexa and try to find new devices, there is unfortunately nothing more.

**Comment by arid154** [comment]
same here :(

**Comment by C64Axel** [comment]
same here :(

**Comment by japesi** [comment]
Same here, too.
Used to work to days ago, now alexa-local does not work anymore. 
Deletig and recreating devices does not help.
Other Alexa nodes (e.g. Node-RED Alexa Home Skill Bridge) still work tho.

**Comment by Matten-Matten** [comment]
bei mir auch das gleiche

**Comment by Samoticha** [comment]
same here seems happen after an firmware update of my echo dot 2

**Comment by hbeekhuis** [comment]
And another one. 
Also renaming the device in Node-red doesn't do the trick. The Alexa app states something like 'device malfunction ' (not able to check exact phrasing right now).
My Sonoffs (who emulate a Philips or wemo device) are still recognized and functional.

**Comment by belialboy** [comment]
Same here. MQTT direct to devices works fine, but Alexa is not recognising devices, and shows them as unresponsive. Does anyone have an interim workaround?

**Comment by eyeson** [comment]
Same here as well! Glad other people are having this - thought I had broken something

**Comment by guardiande** [comment]
Switching to Alexa Home helped for me. Be sure to read the (short) documentation thoroughly regarding port 80.

**Comment by 3ative** [comment]
I got all mine working again by doing this for each 'alexa-local' node:

1.  Copy & Paste the Node 
2.  Hit Deploy - This'll give a new id number
3.  Delete original node
4.  Deploy again
5.  Ask Akexa to discover
6.  Connect new (copied) node back in your flow
    ... "rinse and repeat"

**Comment by belialboy** [comment]
> I got all mine working again by doing this for each 'alexa-local' node:
> 
> 1. Delete all from the Alexa App
> 2. Copy & Paste the Node
> 3. Hit Deploy - This'll give a new id number
> 4. Delete original node
> 5. Deploy again
> 6. Ask Akexa to discover
> 7. Connect new (copied) node back in your flow
>    ... "rinse and repeat"  2-7

Nope, didn't work for me. Got the new p:# in Step 3, but then in Step 6, Alexa does not discover the new node.

I believe that Amazon may have changed the way discovery works, and it's incompatible with the way this node skill functions, hence it's just stopped working. So we're probably in the lap of either the original skill developer or someone with a little more time than me right now to route out and fix the problem.

I'm reluctant to switch over to the "port 80" route, as I have other things running on the same machine (Pi!) that would get nobbled if I did.

**Comment by 3ative** [comment]
@belialboy 
" I believe that Amazon may have changed the way discovery works, and it's incompatible with the way this node skill functions, hence it's just stopped working. So we're probably in the lap of either the original skill developer or someone with a little more time than me right now to route out and fix the problem."

I'm sorry it didn't work for you - as you can see from my video, everything's back working here.

https://www.youtube.com/watch?v=pHKEfkqP_AY

**Comment by hbeekhuis** [comment]
Sadly the same thing here, copied the nodes and saw them getting a new ID, but Alexa (Echo Dot, by the way) isn't finding any 'soft' devices anymore.

Currently don't have the time to look into the other package using the port 80 route (don't really understand it yet based on the brief explanation).

Hopefully some update will make it work automatically again.. :)

**Comment by bastero** [comment]
What i've noticed is that for 'hard' switches using @3ative procedure, Alexa is able to find the switches, however this procedure is not able to get 'soft' switches to be recognized same as @hbeekhuis mentions above.
- 'soft' meaning pseudo switch/trigger (command to make Alexa Local change status of its output)
- 'hard' physical switches
I don't know enough to understand what is going on in the inner workings to know the reason why this is the case. So, this is just what i've observed in case it provided a hint to someone more capable to resolve the issue.

**Comment by nob0dy80** [comment]
look here
https://github.com/originallyus/node-red-contrib-alexa-local/issues/100

**Comment by kxn25** [comment]
So what is the solution of the Problem?

None of my Devices with Alexa-Local in Red Node are working anymore
To my existing Devices came all the same Devices but with Royal Phillips!
I deletet all and Alexa only finds Royal Phillips Devices...

Is the Fix the hole Port reroute thing like @jibbonator mentioned in a diffrend thread the Solution?

> Here´s an Manual for IP Table Routing:
https://o7planning.org/de/11363/redirect-port-80-443-auf-ubuntu-server-mit-iptables
If you want to save at the end again (Beacuse of TCP and UDP), this is the Command: sudo 
 iptables-save

**Comment by kxn25** [comment]
BTW 
neider of the to solution worked for me...

**Comment by 3ative** [comment]
Before you post here...
Scroll up and look for @nob0dy80 and his post (Z 8 days ago) - There you'll find the solution.

**Comment by kxn25** [comment]
Cool finaly i understood how it works for now...
Why is the Issue still open?

**Comment by torinnguyen** [comment]
Please refer to my comment 
[my comment](https://github.com/originallyus/node-red-contrib-alexa-local/issues/100#issuecomment-531777775) in another issue
